// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityAPI.Data;

#nullable disable

namespace UniversityAPI.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    [Migration("20260119112012_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UniversityAPI.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_locked");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("AccountId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("accounts");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            CreatedAt = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@univ.edu",
                            FullName = "System Administrator",
                            IsLocked = false,
                            Password = "$2a$11$K2vXsKpWkGqWy7E.U6TxKelIQR6.WZYpPJG3IWC5FbJXzRYk7DXPK",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            AccountId = 2,
                            CreatedAt = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "department@univ.edu",
                            FullName = "Emily Davis",
                            IsLocked = false,
                            Password = "$2a$11$K2vXsKpWkGqWy7E.U6TxKelIQR6.WZYpPJG3IWC5FbJXzRYk7DXPK",
                            Role = "Department",
                            Username = "department"
                        },
                        new
                        {
                            AccountId = 3,
                            CreatedAt = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "a.turing@univ.edu",
                            FullName = "Dr. Alan Turing",
                            IsLocked = false,
                            Password = "$2a$11$K2vXsKpWkGqWy7E.U6TxKelIQR6.WZYpPJG3IWC5FbJXzRYk7DXPK",
                            Role = "Teacher",
                            Username = "turing"
                        },
                        new
                        {
                            AccountId = 4,
                            CreatedAt = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "k.johnson@univ.edu",
                            FullName = "Dr. Katherine Johnson",
                            IsLocked = false,
                            Password = "$2a$11$K2vXsKpWkGqWy7E.U6TxKelIQR6.WZYpPJG3IWC5FbJXzRYk7DXPK",
                            Role = "Teacher",
                            Username = "johnson"
                        },
                        new
                        {
                            AccountId = 5,
                            CreatedAt = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "g.hopper@univ.edu",
                            FullName = "Dr. Grace Hopper",
                            IsLocked = false,
                            Password = "$2a$11$K2vXsKpWkGqWy7E.U6TxKelIQR6.WZYpPJG3IWC5FbJXzRYk7DXPK",
                            Role = "Teacher",
                            Username = "hopper"
                        },
                        new
                        {
                            AccountId = 6,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice.w@univ.edu",
                            FullName = "Alice Weaver",
                            IsLocked = false,
                            Password = "$2a$11$K2vXsKpWkGqWy7E.U6TxKelIQR6.WZYpPJG3IWC5FbJXzRYk7DXPK",
                            Role = "Student",
                            Username = "alice"
                        },
                        new
                        {
                            AccountId = 7,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob.m@univ.edu",
                            FullName = "Bob Miller",
                            IsLocked = false,
                            Password = "$2a$11$K2vXsKpWkGqWy7E.U6TxKelIQR6.WZYpPJG3IWC5FbJXzRYk7DXPK",
                            Role = "Student",
                            Username = "bob"
                        },
                        new
                        {
                            AccountId = 8,
                            CreatedAt = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "charlie.b@univ.edu",
                            FullName = "Charlie Brown",
                            IsLocked = false,
                            Password = "$2a$11$K2vXsKpWkGqWy7E.U6TxKelIQR6.WZYpPJG3IWC5FbJXzRYk7DXPK",
                            Role = "Student",
                            Username = "charlie"
                        },
                        new
                        {
                            AccountId = 9,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "diana.p@univ.edu",
                            FullName = "Diana Prince",
                            IsLocked = false,
                            Password = "$2a$11$K2vXsKpWkGqWy7E.U6TxKelIQR6.WZYpPJG3IWC5FbJXzRYk7DXPK",
                            Role = "Student",
                            Username = "diana"
                        },
                        new
                        {
                            AccountId = 10,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "evan.j@univ.edu",
                            FullName = "Evan Johnson",
                            IsLocked = false,
                            Password = "$2a$11$K2vXsKpWkGqWy7E.U6TxKelIQR6.WZYpPJG3IWC5FbJXzRYk7DXPK",
                            Role = "Student",
                            Username = "evan"
                        },
                        new
                        {
                            AccountId = 11,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fiona.g@univ.edu",
                            FullName = "Fiona Green",
                            IsLocked = false,
                            Password = "$2a$11$K2vXsKpWkGqWy7E.U6TxKelIQR6.WZYpPJG3IWC5FbJXzRYk7DXPK",
                            Role = "Student",
                            Username = "fiona"
                        },
                        new
                        {
                            AccountId = 12,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "george.h@univ.edu",
                            FullName = "George Harris",
                            IsLocked = false,
                            Password = "$2a$11$K2vXsKpWkGqWy7E.U6TxKelIQR6.WZYpPJG3IWC5FbJXzRYk7DXPK",
                            Role = "Student",
                            Username = "george"
                        },
                        new
                        {
                            AccountId = 13,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "helena.k@univ.edu",
                            FullName = "Helena King",
                            IsLocked = false,
                            Password = "$2a$11$K2vXsKpWkGqWy7E.U6TxKelIQR6.WZYpPJG3IWC5FbJXzRYk7DXPK",
                            Role = "Student",
                            Username = "helena"
                        },
                        new
                        {
                            AccountId = 14,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "isaac.l@univ.edu",
                            FullName = "Isaac Lee",
                            IsLocked = false,
                            Password = "$2a$11$K2vXsKpWkGqWy7E.U6TxKelIQR6.WZYpPJG3IWC5FbJXzRYk7DXPK",
                            Role = "Student",
                            Username = "isaac"
                        },
                        new
                        {
                            AccountId = 15,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "julia.m@univ.edu",
                            FullName = "Julia Martin",
                            IsLocked = false,
                            Password = "$2a$11$K2vXsKpWkGqWy7E.U6TxKelIQR6.WZYpPJG3IWC5FbJXzRYk7DXPK",
                            Role = "Student",
                            Username = "julia"
                        },
                        new
                        {
                            AccountId = 16,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kevin.n@univ.edu",
                            FullName = "Kevin Nelson",
                            IsLocked = false,
                            Password = "$2a$11$K2vXsKpWkGqWy7E.U6TxKelIQR6.WZYpPJG3IWC5FbJXzRYk7DXPK",
                            Role = "Student",
                            Username = "kevin"
                        },
                        new
                        {
                            AccountId = 17,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laura.o@univ.edu",
                            FullName = "Laura Owen",
                            IsLocked = false,
                            Password = "$2a$11$K2vXsKpWkGqWy7E.U6TxKelIQR6.WZYpPJG3IWC5FbJXzRYk7DXPK",
                            Role = "Student",
                            Username = "laura"
                        },
                        new
                        {
                            AccountId = 18,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michael.p@univ.edu",
                            FullName = "Michael Parker",
                            IsLocked = false,
                            Password = "$2a$11$K2vXsKpWkGqWy7E.U6TxKelIQR6.WZYpPJG3IWC5FbJXzRYk7DXPK",
                            Role = "Student",
                            Username = "michael"
                        },
                        new
                        {
                            AccountId = 19,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nancy.q@univ.edu",
                            FullName = "Nancy Quinn",
                            IsLocked = false,
                            Password = "$2a$11$K2vXsKpWkGqWy7E.U6TxKelIQR6.WZYpPJG3IWC5FbJXzRYk7DXPK",
                            Role = "Student",
                            Username = "nancy"
                        },
                        new
                        {
                            AccountId = 20,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "oscar.r@univ.edu",
                            FullName = "Oscar Roberts",
                            IsLocked = false,
                            Password = "$2a$11$K2vXsKpWkGqWy7E.U6TxKelIQR6.WZYpPJG3IWC5FbJXzRYk7DXPK",
                            Role = "Student",
                            Username = "oscar"
                        },
                        new
                        {
                            AccountId = 21,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "paula.s@univ.edu",
                            FullName = "Paula Scott",
                            IsLocked = false,
                            Password = "$2a$11$K2vXsKpWkGqWy7E.U6TxKelIQR6.WZYpPJG3IWC5FbJXzRYk7DXPK",
                            Role = "Student",
                            Username = "paula"
                        },
                        new
                        {
                            AccountId = 22,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "quinn.t@univ.edu",
                            FullName = "Quinn Taylor",
                            IsLocked = false,
                            Password = "$2a$11$K2vXsKpWkGqWy7E.U6TxKelIQR6.WZYpPJG3IWC5FbJXzRYk7DXPK",
                            Role = "Student",
                            Username = "quinn"
                        });
                });

            modelBuilder.Entity("UniversityAPI.Models.Class", b =>
                {
                    b.Property<string>("ClassId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("class_id");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("class_name");

                    b.Property<int>("CohortYear")
                        .HasColumnType("int")
                        .HasColumnName("cohort_year");

                    b.Property<string>("DeptId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("dept_id");

                    b.HasKey("ClassId");

                    b.HasIndex("DeptId");

                    b.ToTable("classes");

                    b.HasData(
                        new
                        {
                            ClassId = "CS2024A",
                            ClassName = "Computer Science 2024 - Section A",
                            CohortYear = 2024,
                            DeptId = "CS"
                        },
                        new
                        {
                            ClassId = "CS2024B",
                            ClassName = "Computer Science 2024 - Section B",
                            CohortYear = 2024,
                            DeptId = "CS"
                        },
                        new
                        {
                            ClassId = "MATH2024",
                            ClassName = "Mathematics 2024",
                            CohortYear = 2024,
                            DeptId = "MATH"
                        },
                        new
                        {
                            ClassId = "PHYS2023",
                            ClassName = "Physics 2023",
                            CohortYear = 2023,
                            DeptId = "PHYS"
                        });
                });

            modelBuilder.Entity("UniversityAPI.Models.Course", b =>
                {
                    b.Property<string>("CourseId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("course_id");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("course_name");

                    b.Property<int>("Credits")
                        .HasColumnType("int")
                        .HasColumnName("credits");

                    b.Property<string>("DeptId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("dept_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.HasKey("CourseId");

                    b.HasIndex("DeptId");

                    b.ToTable("courses");

                    b.HasData(
                        new
                        {
                            CourseId = "CS101",
                            CourseName = "Introduction to Computer Science",
                            Credits = 4,
                            DeptId = "CS",
                            Description = "Foundational concepts in computing"
                        },
                        new
                        {
                            CourseId = "CS201",
                            CourseName = "Data Structures & Algorithms",
                            Credits = 4,
                            DeptId = "CS",
                            Description = "Core data structures and algorithms"
                        },
                        new
                        {
                            CourseId = "CS450",
                            CourseName = "Machine Learning",
                            Credits = 4,
                            DeptId = "CS",
                            Description = "Fundamentals of machine learning"
                        },
                        new
                        {
                            CourseId = "MATH201",
                            CourseName = "Linear Algebra",
                            Credits = 3,
                            DeptId = "MATH",
                            Description = "Vectors, matrices, and linear transformations"
                        },
                        new
                        {
                            CourseId = "ENG102",
                            CourseName = "Academic Writing",
                            Credits = 3,
                            DeptId = "ENG",
                            Description = "Research and academic writing skills"
                        });
                });

            modelBuilder.Entity("UniversityAPI.Models.Department", b =>
                {
                    b.Property<string>("DeptId")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("dept_id");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("dept_name");

                    b.HasKey("DeptId");

                    b.ToTable("departments");

                    b.HasData(
                        new
                        {
                            DeptId = "CS",
                            DeptName = "Computer Science"
                        },
                        new
                        {
                            DeptId = "MATH",
                            DeptName = "Mathematics"
                        },
                        new
                        {
                            DeptId = "PHYS",
                            DeptName = "Physics"
                        },
                        new
                        {
                            DeptId = "ENG",
                            DeptName = "English Literature"
                        },
                        new
                        {
                            DeptId = "BIO",
                            DeptName = "Biology"
                        });
                });

            modelBuilder.Entity("UniversityAPI.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("enrollment_id");

                    b.Property<DateTime>("EnrollDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("enroll_date");

                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("student_id");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("SectionId");

                    b.HasIndex("StudentId", "SectionId")
                        .IsUnique();

                    b.ToTable("enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            EnrollDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            Status = "Enrolled",
                            StudentId = "2024001"
                        },
                        new
                        {
                            EnrollmentId = 2,
                            EnrollDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            Status = "Enrolled",
                            StudentId = "2024002"
                        },
                        new
                        {
                            EnrollmentId = 3,
                            EnrollDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            Status = "Enrolled",
                            StudentId = "2024003"
                        },
                        new
                        {
                            EnrollmentId = 4,
                            EnrollDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            Status = "Enrolled",
                            StudentId = "2024004"
                        },
                        new
                        {
                            EnrollmentId = 5,
                            EnrollDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            Status = "Enrolled",
                            StudentId = "2024005"
                        },
                        new
                        {
                            EnrollmentId = 6,
                            EnrollDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            Status = "Enrolled",
                            StudentId = "2024006"
                        },
                        new
                        {
                            EnrollmentId = 7,
                            EnrollDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            Status = "Enrolled",
                            StudentId = "2024007"
                        },
                        new
                        {
                            EnrollmentId = 8,
                            EnrollDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            Status = "Enrolled",
                            StudentId = "2024008"
                        },
                        new
                        {
                            EnrollmentId = 9,
                            EnrollDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            Status = "Enrolled",
                            StudentId = "2024013"
                        },
                        new
                        {
                            EnrollmentId = 10,
                            EnrollDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            Status = "Enrolled",
                            StudentId = "2024014"
                        },
                        new
                        {
                            EnrollmentId = 11,
                            EnrollDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            Status = "Enrolled",
                            StudentId = "2024015"
                        },
                        new
                        {
                            EnrollmentId = 12,
                            EnrollDate = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            Status = "Enrolled",
                            StudentId = "2023015"
                        },
                        new
                        {
                            EnrollmentId = 13,
                            EnrollDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            Status = "Enrolled",
                            StudentId = "2024016"
                        },
                        new
                        {
                            EnrollmentId = 14,
                            EnrollDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            Status = "Enrolled",
                            StudentId = "2024001"
                        },
                        new
                        {
                            EnrollmentId = 15,
                            EnrollDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            Status = "Enrolled",
                            StudentId = "2024002"
                        },
                        new
                        {
                            EnrollmentId = 16,
                            EnrollDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            Status = "Enrolled",
                            StudentId = "2024003"
                        },
                        new
                        {
                            EnrollmentId = 17,
                            EnrollDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            Status = "Enrolled",
                            StudentId = "2024004"
                        },
                        new
                        {
                            EnrollmentId = 18,
                            EnrollDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            Status = "Enrolled",
                            StudentId = "2024005"
                        },
                        new
                        {
                            EnrollmentId = 19,
                            EnrollDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            Status = "Enrolled",
                            StudentId = "2024006"
                        },
                        new
                        {
                            EnrollmentId = 20,
                            EnrollDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            Status = "Enrolled",
                            StudentId = "2024007"
                        },
                        new
                        {
                            EnrollmentId = 21,
                            EnrollDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            Status = "Enrolled",
                            StudentId = "2024008"
                        },
                        new
                        {
                            EnrollmentId = 22,
                            EnrollDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            Status = "Enrolled",
                            StudentId = "2024009"
                        },
                        new
                        {
                            EnrollmentId = 23,
                            EnrollDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            Status = "Enrolled",
                            StudentId = "2024010"
                        },
                        new
                        {
                            EnrollmentId = 24,
                            EnrollDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            Status = "Enrolled",
                            StudentId = "2024011"
                        },
                        new
                        {
                            EnrollmentId = 25,
                            EnrollDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            Status = "Enrolled",
                            StudentId = "2024012"
                        },
                        new
                        {
                            EnrollmentId = 26,
                            EnrollDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            Status = "Enrolled",
                            StudentId = "2024001"
                        },
                        new
                        {
                            EnrollmentId = 27,
                            EnrollDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            Status = "Enrolled",
                            StudentId = "2024002"
                        },
                        new
                        {
                            EnrollmentId = 28,
                            EnrollDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            Status = "Enrolled",
                            StudentId = "2024003"
                        },
                        new
                        {
                            EnrollmentId = 29,
                            EnrollDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            Status = "Enrolled",
                            StudentId = "2024004"
                        });
                });

            modelBuilder.Entity("UniversityAPI.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("grade_id");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int")
                        .HasColumnName("enrollment_id");

                    b.Property<decimal?>("Final")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("final");

                    b.Property<decimal?>("GpaPoint")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("gpa_point");

                    b.Property<string>("LetterGrade")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("letter_grade");

                    b.Property<decimal?>("Midterm")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("midterm");

                    b.Property<decimal?>("Other")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("other");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("updated_by");

                    b.HasKey("GradeId");

                    b.HasIndex("EnrollmentId")
                        .IsUnique();

                    b.ToTable("grades");

                    b.HasData(
                        new
                        {
                            GradeId = 1,
                            EnrollmentId = 1,
                            Final = 88m,
                            GpaPoint = 3.5m,
                            LetterGrade = "B+",
                            Midterm = 85m,
                            Other = 90m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3712),
                            UpdatedBy = "T001"
                        },
                        new
                        {
                            GradeId = 2,
                            EnrollmentId = 2,
                            Final = 90m,
                            GpaPoint = 3.7m,
                            LetterGrade = "A-",
                            Midterm = 92m,
                            Other = 88m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3716),
                            UpdatedBy = "T001"
                        },
                        new
                        {
                            GradeId = 3,
                            EnrollmentId = 3,
                            Final = 82m,
                            GpaPoint = 3.0m,
                            LetterGrade = "B",
                            Midterm = 78m,
                            Other = 80m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3719),
                            UpdatedBy = "T001"
                        },
                        new
                        {
                            GradeId = 4,
                            EnrollmentId = 4,
                            Final = 91m,
                            GpaPoint = 3.6m,
                            LetterGrade = "A-",
                            Midterm = 88m,
                            Other = 89m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3723),
                            UpdatedBy = "T001"
                        },
                        new
                        {
                            GradeId = 5,
                            EnrollmentId = 5,
                            Final = 79m,
                            GpaPoint = 2.9m,
                            LetterGrade = "C+",
                            Midterm = 75m,
                            Other = 77m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3725),
                            UpdatedBy = "T001"
                        },
                        new
                        {
                            GradeId = 6,
                            EnrollmentId = 6,
                            Final = 93m,
                            GpaPoint = 3.8m,
                            LetterGrade = "A",
                            Midterm = 91m,
                            Other = 92m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3728),
                            UpdatedBy = "T001"
                        },
                        new
                        {
                            GradeId = 7,
                            EnrollmentId = 7,
                            Final = 85m,
                            GpaPoint = 3.3m,
                            LetterGrade = "B",
                            Midterm = 82m,
                            Other = 84m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3731),
                            UpdatedBy = "T001"
                        },
                        new
                        {
                            GradeId = 8,
                            EnrollmentId = 8,
                            Final = 87m,
                            GpaPoint = 3.5m,
                            LetterGrade = "B+",
                            Midterm = 89m,
                            Other = 88m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3733),
                            UpdatedBy = "T001"
                        },
                        new
                        {
                            GradeId = 9,
                            EnrollmentId = 9,
                            Final = 83m,
                            GpaPoint = 3.2m,
                            LetterGrade = "B",
                            Midterm = 80m,
                            Other = 81m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3736),
                            UpdatedBy = "T003"
                        },
                        new
                        {
                            GradeId = 10,
                            EnrollmentId = 10,
                            Final = 89m,
                            GpaPoint = 3.5m,
                            LetterGrade = "B+",
                            Midterm = 86m,
                            Other = 87m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3738),
                            UpdatedBy = "T003"
                        },
                        new
                        {
                            GradeId = 11,
                            EnrollmentId = 11,
                            Final = 92m,
                            GpaPoint = 3.9m,
                            LetterGrade = "A",
                            Midterm = 94m,
                            Other = 93m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3741),
                            UpdatedBy = "T003"
                        },
                        new
                        {
                            GradeId = 12,
                            EnrollmentId = 12,
                            Final = 80m,
                            GpaPoint = 2.9m,
                            LetterGrade = "C+",
                            Midterm = 77m,
                            Other = 78m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3747),
                            UpdatedBy = "T003"
                        },
                        new
                        {
                            GradeId = 13,
                            EnrollmentId = 13,
                            Final = 86m,
                            GpaPoint = 3.3m,
                            LetterGrade = "B",
                            Midterm = 83m,
                            Other = 85m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3750),
                            UpdatedBy = "T003"
                        },
                        new
                        {
                            GradeId = 14,
                            EnrollmentId = 14,
                            Final = 91m,
                            GpaPoint = 3.6m,
                            LetterGrade = "A-",
                            Midterm = 88m,
                            Other = 90m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3752),
                            UpdatedBy = "T001"
                        },
                        new
                        {
                            GradeId = 15,
                            EnrollmentId = 15,
                            Final = 82m,
                            GpaPoint = 3.2m,
                            LetterGrade = "B",
                            Midterm = 85m,
                            Other = 80m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3756),
                            UpdatedBy = "T001"
                        },
                        new
                        {
                            GradeId = 16,
                            EnrollmentId = 16,
                            Final = 81m,
                            GpaPoint = 3.0m,
                            LetterGrade = "B",
                            Midterm = 79m,
                            Other = 80m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3758),
                            UpdatedBy = "T001"
                        },
                        new
                        {
                            GradeId = 17,
                            EnrollmentId = 17,
                            Final = 94m,
                            GpaPoint = 3.8m,
                            LetterGrade = "A",
                            Midterm = 92m,
                            Other = 93m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3761),
                            UpdatedBy = "T001"
                        },
                        new
                        {
                            GradeId = 18,
                            EnrollmentId = 18,
                            Final = 78m,
                            GpaPoint = 2.8m,
                            LetterGrade = "C+",
                            Midterm = 76m,
                            Other = 77m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3763),
                            UpdatedBy = "T001"
                        },
                        new
                        {
                            GradeId = 19,
                            EnrollmentId = 19,
                            Final = 89m,
                            GpaPoint = 3.5m,
                            LetterGrade = "B+",
                            Midterm = 87m,
                            Other = 88m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3766),
                            UpdatedBy = "T001"
                        },
                        new
                        {
                            GradeId = 20,
                            EnrollmentId = 20,
                            Final = 86m,
                            GpaPoint = 3.3m,
                            LetterGrade = "B",
                            Midterm = 84m,
                            Other = 85m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3768),
                            UpdatedBy = "T001"
                        },
                        new
                        {
                            GradeId = 21,
                            EnrollmentId = 21,
                            Final = 88m,
                            GpaPoint = 3.6m,
                            LetterGrade = "A-",
                            Midterm = 90m,
                            Other = 89m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3771),
                            UpdatedBy = "T001"
                        },
                        new
                        {
                            GradeId = 22,
                            EnrollmentId = 22,
                            Final = 92m,
                            GpaPoint = 3.7m,
                            LetterGrade = "A-",
                            Midterm = 89m,
                            Other = 91m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3773),
                            UpdatedBy = "T002"
                        },
                        new
                        {
                            GradeId = 23,
                            EnrollmentId = 23,
                            Final = 84m,
                            GpaPoint = 3.2m,
                            LetterGrade = "B",
                            Midterm = 81m,
                            Other = 83m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3775),
                            UpdatedBy = "T002"
                        },
                        new
                        {
                            GradeId = 24,
                            EnrollmentId = 24,
                            Final = 95m,
                            GpaPoint = 3.9m,
                            LetterGrade = "A",
                            Midterm = 93m,
                            Other = 94m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3778),
                            UpdatedBy = "T002"
                        },
                        new
                        {
                            GradeId = 25,
                            EnrollmentId = 25,
                            Final = 77m,
                            GpaPoint = 2.7m,
                            LetterGrade = "C",
                            Midterm = 74m,
                            Other = 75m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3780),
                            UpdatedBy = "T002"
                        },
                        new
                        {
                            GradeId = 26,
                            EnrollmentId = 26,
                            Final = 88m,
                            GpaPoint = 3.4m,
                            LetterGrade = "B+",
                            Midterm = 86m,
                            Other = 87m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3783),
                            UpdatedBy = "T002"
                        },
                        new
                        {
                            GradeId = 27,
                            EnrollmentId = 27,
                            Final = 91m,
                            GpaPoint = 3.7m,
                            LetterGrade = "A-",
                            Midterm = 90m,
                            Other = 91m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3785),
                            UpdatedBy = "T002"
                        },
                        new
                        {
                            GradeId = 28,
                            EnrollmentId = 28,
                            Final = 85m,
                            GpaPoint = 3.3m,
                            LetterGrade = "B",
                            Midterm = 82m,
                            Other = 84m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3788),
                            UpdatedBy = "T002"
                        },
                        new
                        {
                            GradeId = 29,
                            EnrollmentId = 29,
                            Final = 90m,
                            GpaPoint = 3.5m,
                            LetterGrade = "B+",
                            Midterm = 87m,
                            Other = 88m,
                            UpdatedAt = new DateTime(2026, 1, 19, 11, 20, 12, 408, DateTimeKind.Utc).AddTicks(3790),
                            UpdatedBy = "T002"
                        });
                });

            modelBuilder.Entity("UniversityAPI.Models.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("course_id");

                    b.Property<bool>("IsGradeLocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_grade_locked");

                    b.Property<string>("Room")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("room");

                    b.Property<string>("Schedule")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("schedule");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("semester");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("teacher_id");

                    b.HasKey("SectionId");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("sections");

                    b.HasData(
                        new
                        {
                            SectionId = 1,
                            Capacity = 50,
                            CourseId = "CS101",
                            IsGradeLocked = false,
                            Room = "Science 101",
                            Schedule = "Mon, Wed 10:00-11:30",
                            Semester = "Spring2026",
                            Status = "Open",
                            TeacherId = "T001"
                        },
                        new
                        {
                            SectionId = 2,
                            Capacity = 50,
                            CourseId = "CS101",
                            IsGradeLocked = false,
                            Room = "Science 102",
                            Schedule = "Tue, Thu 14:00-15:30",
                            Semester = "Spring2026",
                            Status = "Closed",
                            TeacherId = "T003"
                        },
                        new
                        {
                            SectionId = 3,
                            Capacity = 40,
                            CourseId = "CS201",
                            IsGradeLocked = false,
                            Room = "Tech Lab 201",
                            Schedule = "Mon, Wed, Fri 09:00-10:00",
                            Semester = "Spring2026",
                            Status = "Open",
                            TeacherId = "T001"
                        },
                        new
                        {
                            SectionId = 4,
                            Capacity = 45,
                            CourseId = "MATH201",
                            IsGradeLocked = false,
                            Room = "Math Hall 101",
                            Schedule = "Tue, Thu 10:00-11:30",
                            Semester = "Spring2026",
                            Status = "Open",
                            TeacherId = "T002"
                        });
                });

            modelBuilder.Entity("UniversityAPI.Models.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("student_id");

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("class_id");

                    b.Property<string>("DeptId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("dept_id");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("fullname");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("StudentId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("ClassId");

                    b.HasIndex("DeptId");

                    b.ToTable("students");

                    b.HasData(
                        new
                        {
                            StudentId = "2024001",
                            AccountId = 6,
                            ClassId = "CS2024A",
                            DeptId = "CS",
                            Dob = new DateTime(2004, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice.w@univ.edu",
                            Fullname = "Alice Weaver",
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = "2024002",
                            AccountId = 7,
                            ClassId = "CS2024A",
                            DeptId = "CS",
                            Dob = new DateTime(2004, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob.m@univ.edu",
                            Fullname = "Bob Miller",
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = "2024003",
                            AccountId = 9,
                            ClassId = "CS2024A",
                            DeptId = "CS",
                            Dob = new DateTime(2004, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "diana.p@univ.edu",
                            Fullname = "Diana Prince",
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = "2024004",
                            AccountId = 10,
                            ClassId = "CS2024A",
                            DeptId = "CS",
                            Dob = new DateTime(2004, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "evan.j@univ.edu",
                            Fullname = "Evan Johnson",
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = "2024005",
                            AccountId = 11,
                            ClassId = "CS2024A",
                            DeptId = "CS",
                            Dob = new DateTime(2004, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fiona.g@univ.edu",
                            Fullname = "Fiona Green",
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = "2024006",
                            AccountId = 12,
                            ClassId = "CS2024A",
                            DeptId = "CS",
                            Dob = new DateTime(2004, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "george.h@univ.edu",
                            Fullname = "George Harris",
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = "2024007",
                            AccountId = 13,
                            ClassId = "CS2024A",
                            DeptId = "CS",
                            Dob = new DateTime(2004, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "helena.k@univ.edu",
                            Fullname = "Helena King",
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = "2024008",
                            AccountId = 14,
                            ClassId = "CS2024A",
                            DeptId = "CS",
                            Dob = new DateTime(2004, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "isaac.l@univ.edu",
                            Fullname = "Isaac Lee",
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = "2024009",
                            AccountId = 15,
                            ClassId = "MATH2024",
                            DeptId = "MATH",
                            Dob = new DateTime(2004, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "julia.m@univ.edu",
                            Fullname = "Julia Martin",
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = "2024010",
                            AccountId = 16,
                            ClassId = "MATH2024",
                            DeptId = "MATH",
                            Dob = new DateTime(2004, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kevin.n@univ.edu",
                            Fullname = "Kevin Nelson",
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = "2024011",
                            AccountId = 17,
                            ClassId = "MATH2024",
                            DeptId = "MATH",
                            Dob = new DateTime(2004, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laura.o@univ.edu",
                            Fullname = "Laura Owen",
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = "2024012",
                            AccountId = 18,
                            ClassId = "MATH2024",
                            DeptId = "MATH",
                            Dob = new DateTime(2004, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michael.p@univ.edu",
                            Fullname = "Michael Parker",
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = "2024013",
                            AccountId = 19,
                            ClassId = "CS2024B",
                            DeptId = "CS",
                            Dob = new DateTime(2004, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nancy.q@univ.edu",
                            Fullname = "Nancy Quinn",
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = "2024014",
                            AccountId = 20,
                            ClassId = "CS2024B",
                            DeptId = "CS",
                            Dob = new DateTime(2004, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "oscar.r@univ.edu",
                            Fullname = "Oscar Roberts",
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = "2024015",
                            AccountId = 21,
                            ClassId = "CS2024B",
                            DeptId = "CS",
                            Dob = new DateTime(2004, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "paula.s@univ.edu",
                            Fullname = "Paula Scott",
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = "2023015",
                            AccountId = 8,
                            ClassId = "PHYS2023",
                            DeptId = "PHYS",
                            Dob = new DateTime(2003, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "charlie.b@univ.edu",
                            Fullname = "Charlie Brown",
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = "2024016",
                            AccountId = 22,
                            ClassId = "CS2024B",
                            DeptId = "ENG",
                            Dob = new DateTime(2004, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "quinn.t@univ.edu",
                            Fullname = "Quinn Taylor",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("UniversityAPI.Models.Teacher", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("teacher_id");

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<string>("DeptId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("dept_id");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("TeacherId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("DeptId");

                    b.ToTable("teachers");

                    b.HasData(
                        new
                        {
                            TeacherId = "T001",
                            AccountId = 3,
                            DeptId = "CS",
                            Email = "a.turing@univ.edu",
                            FullName = "Dr. Alan Turing",
                            Status = "Active"
                        },
                        new
                        {
                            TeacherId = "T002",
                            AccountId = 4,
                            DeptId = "MATH",
                            Email = "k.johnson@univ.edu",
                            FullName = "Dr. Katherine Johnson",
                            Status = "Active"
                        },
                        new
                        {
                            TeacherId = "T003",
                            AccountId = 5,
                            DeptId = "CS",
                            Email = "g.hopper@univ.edu",
                            FullName = "Dr. Grace Hopper",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("UniversityAPI.Models.Class", b =>
                {
                    b.HasOne("UniversityAPI.Models.Department", "Department")
                        .WithMany("Classes")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("UniversityAPI.Models.Course", b =>
                {
                    b.HasOne("UniversityAPI.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("UniversityAPI.Models.Enrollment", b =>
                {
                    b.HasOne("UniversityAPI.Models.Section", "Section")
                        .WithMany("Enrollments")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityAPI.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniversityAPI.Models.Grade", b =>
                {
                    b.HasOne("UniversityAPI.Models.Enrollment", "Enrollment")
                        .WithOne("Grade")
                        .HasForeignKey("UniversityAPI.Models.Grade", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("UniversityAPI.Models.Section", b =>
                {
                    b.HasOne("UniversityAPI.Models.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityAPI.Models.Teacher", "Teacher")
                        .WithMany("Sections")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("UniversityAPI.Models.Student", b =>
                {
                    b.HasOne("UniversityAPI.Models.Account", "Account")
                        .WithOne("Student")
                        .HasForeignKey("UniversityAPI.Models.Student", "AccountId");

                    b.HasOne("UniversityAPI.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityAPI.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Class");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("UniversityAPI.Models.Teacher", b =>
                {
                    b.HasOne("UniversityAPI.Models.Account", "Account")
                        .WithOne("Teacher")
                        .HasForeignKey("UniversityAPI.Models.Teacher", "AccountId");

                    b.HasOne("UniversityAPI.Models.Department", "Department")
                        .WithMany("Teachers")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("UniversityAPI.Models.Account", b =>
                {
                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("UniversityAPI.Models.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("UniversityAPI.Models.Course", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("UniversityAPI.Models.Department", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Courses");

                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("UniversityAPI.Models.Enrollment", b =>
                {
                    b.Navigation("Grade");
                });

            modelBuilder.Entity("UniversityAPI.Models.Section", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("UniversityAPI.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("UniversityAPI.Models.Teacher", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
